=== Vue.js Components with Dynamic Content

Next we add event handling and dynamic content to our events view.

First, let's make the event list dynamic instead of hard-coding it in the HTML.
Add the following code in the `<script>` block...

[source,javascript]
----
<script>
export default {
  name: "events",
  data() {
    return {
      events: [
        { type: "IN_PERSON", name: "My in-person event", date: "2024-11-15", startTime: "13:35:00", endTime: "15:25:00", registrationLimit: 1, location: "McGill" },
        { type: "ONLINE", name: "My online event", date: "2024-11-16", startTime: "12:00:00", endTime: "13:00:00", registrationLimit: 100, location: "Zoom" },
      ],
    };
  }
}
</script>
----

...and replace the hard-coded `<table>` element with the following table:

[source,html]
----
<table>
  <tbody>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Type</th>
    </tr>
    <tr v-for="e in events">
      <td>{{ e.name }}</td>
      <td>{{ e.date }}</td>
      <td>{{ e.type === "IN_PERSON" ? "In person" : "Online" }}</td>
    </tr>
  </tbody>
</table>
----

Vue.js will automatically inject a new `<tr>` element for each entry in the `events` array (defined above in the `<script>` block).
The "mustache variables" (e.g., `{{ e.name }}`) will be replaced with the value for the event `e` in the current row.

To implement event creation, we define variables to hold the values entered by the user...

[source,javascript]
----
export default {
  // ...
  data() {
    return {
      events: /* ... */,
      newEventType: "IN_PERSON",
      newEventName: null,
      newEventDate: null,
      newEventStartTime: null,
      newEventEndTime: null,
      newEventRegLimit: null,
      newEventLocation: null
    };
  },
  // ...
}
----

...we define methods `createEvent()` and `clearInputs()`...

[source,javascript]
----
export default {
  // ...
  methods: {
    createEvent() {
      const newEvent = {
        type: this.newEventType,
        name: this.newEventName,
        date: this.newEventDate,
        startTime: this.newEventStartTime,
        endTime: this.newEventEndTime,
        registrationLimit: this.newEventRegLimit,
        location: this.newEventLocation
      };
      this.events.push(newEvent);
    },
    clearInputs() {
      this.newEventType = "IN_PERSON";
      this.newEventName = null;
      this.newEventDate = null;
      this.newEventStartTime = null;
      this.newEventEndTime = null;
      this.newEventRegLimit = null;
      this.newEventLocation = null;
    },
    isEventValid() {
      return this.newEventName
        && this.newEventDate
        && this.newEventStartTime
        && this.newEventRegLimit
        && this.newEventLocation;
    }
  }
}
----

...and we bind these new variables and methods to the input elements using `v-bind` and `@click`, respectively.

[source,html]
----
<div>
  <select v-model="newEventType">
    <option value="IN_PERSON">In person</option>
    <option value="ONLINE">Online</option>
  </select>
  <input type="text" placeholder="Name" v-model="newEventName" />
  <input type="date" placeholder="Date" v-model="newEventDate" />
  <input type="time" placeholder="Start Time" v-model="newEventStartTime" />
  <input type="time" placeholder="End Time" v-model="newEventEndTime" />
  <input type="text" placeholder="Registration Limit" v-model="newEventRegLimit" />
  <input type="text" placeholder="Location" v-model="newEventLocation" />
  <button id="create-btn" @click="createEvent" v-bind:disabled="!isEventValid()">Create Event</button>
  <button class="danger-btn" @click="clearInputs">Clear</button>
</div>
----

Whenever the button is clicked, the method specified by the `@click` attribute (in this case, `createEvent` or `clearInputs`) will be called.
`createEvent` accesses the values entered by the user via `this.newEventName`, `this.newEventDate`, etc.
It then adds a new event to the array, which will result in the DOM being updated.
To clear the inputs, `clearInputs` simply updates the variables `this.newEventName`, `this.newEventDate`, etc.

Notice that we also disable the button in case the user has not entered all the required information yet.
We take advantage of the fact that empty strings, `null`, and `undefined` are all "falsy" values; that is, `isEventValid` will return `false` if any of the values are empty, `null`, or `undefined`.

IMPORTANT: The `v-model` attribute implements *two-way data binding*.
If our JavaScript code updates one of the variables, the HTML will be updated accordingly.
Conversely, if the users types something, the value of the corresponding variable will be updated.
