=== Calling Backend Services

Next we change our frontend to issue calls to the backend via the Rest API provided by the Java Spring framework. Please refer to the section 3.6.2 where we enabled the Cross-Origin Resource Sharing at the controller level using '@CrossOrigin' notation.

==== Install additional dependencies

. Add Axios as a dependency. We will use Axios for issuing REST API calls.
```bash
npm install axios@1.5
```

==== Calling backend services in from Vue.js components
We need to modify our frontend to make calls to backend services.

. Open **registration.js** and add the following content to the beginning:
+
[source,javascript]
----
import axios from 'axios'

const AXIOS = axios.create({
  baseURL: "http://localhost:8080"
})
----

. Now navigate to the **created** function, and replace existing content
with the following lines:
+
[source,javascript]
----
  created: function () {
    // Initializing persons from backend
    AXIOS.get('/persons')
    .then(response => {
      // JSON responses are automatically parsed.
      this.persons = response.data
    })
    .catch(e => {
      this.errorPerson = e
    })
    // Initializing events
    AXIOS.get('/events')
    .then(response => {
      this.events = response.data
    })
    .catch(e => {
      this.errorEvent = e
      // this.errors.push(e)
    })
  }
----

. Navigate to the **createPerson()** method and change its content as follows:
+
[source,javascript]
----
createPerson: function (personName) {
      AXIOS.post('/persons/'.concat(personName), {}, {})
        .then(response => {
        // JSON responses are automatically parsed.
          this.persons.push(response.data)
          this.errorPerson = ''
          this.newPerson = ''
        })
        .catch(e => {
          const errorMsg = e.response.data.message
          console.log(errorMsg)
          this.errorPerson = errorMsg
        })
    }
----

. Run the frontend application and check that
* New people can be added
* They immediately appear in the people list.

Note that, at first, you will likely run into CORS (link:https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS[Cross-Origin Resource Sharing]) errors.
You must add the `@CrossOrigin` annotation to your controller classes to allow requests from your frontend.

[NOTE]
You can also use wildcards in the `@CrossOrigin` annotation, as in `@CrossOrigin(origin = "*")`.
This allows cross-origin requests from *any* domain, which is less secure but possibly more convenient.

+
[source,java]
----
package ca.mcgill.ecse321.eventregistration.controller;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RestController;

@CrossOrigin(origins = "http://localhost:8087")
@RestController
public class EventRegistrationRestController {
  // ...
}
----
